{
    'name': 'Project Phases Management',
    'version': '13.1.0',
    "category": "website",
    'summary': 'Project Phases Management',
    "description": """Project management using project methodologies.""",
    "author": "Planet-odoo",
    'website': 'http://www.planet-odoo.com/',
    'depends': ['base', 'web', 'project'],
    'data': [
             'data/project_dashboard.xml',
             'security/project_user_acess.xml',
             'security/ir.model.access.csv',
             # 'views/project_phases_view.xml',
             'views/project_dashboard.xml',
             'views/project_inherit_views.xml',
             'views/project_stages_view.xml',
         ],
    'demo': [],
    'installable': True,
    'auto_install': False,
    'application': True,
}
