{
    'name': 'Project Phases Management',
    'version': '13.1.0',
    "category": "website",
    'summary': 'Project Phases Management',
    "description": """Project management using project methodologies.""",
    "author": "Planet-odoo",
    'website': 'http://www.planet-odoo.com/',
    'depends': ['base', 'web', 'project', 'account','hr_timesheet', 'calendar'],
    'data': [
        'data/project_dashboard.xml',
        'data/chat_message.xml',
        'data/mail_project.xml',
        'data/delete_announcements.xml',
        'security/project_user_acess.xml',
        'security/ir.model.access.csv',
        'views/res_partner_inherit_views.xml',
        'wizards/message_view.xml',
        'views/project_dashboard.xml',
        'views/milestone_view.xml',
        'views/project_inherit_views.xml',
        'views/project_stages_view.xml',
        'views/task_inherit_views.xml',
        'wizards/announcement_views.xml',
        'views/announcement_panel.xml',
        'views/project_planner_views.xml',

    ],
    'demo': [],
    'installable': True,
    'auto_install': False,
    'application': True,
}
